# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-ECDSA
version:      0.021
version_from: lib/Crypt/ECDSA.pm
installdirs:  site
requires:
    Carp:                          0
    Data::Compare:                 0
    Digest::SHA:                   0
    Math::BigInt:                  0
    Math::BigInt::GMP:             0
    Math::BigInt::Random:          0
    Math::GMP:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
